apps/xee/lib/xee_web/router.ex
defmodule XeeWeb.Router do
  use XeeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :js do
    plug :accepts, ["js"]
  end

  scope "/", XeeWeb do
    pipe_through :js
    get "/experiment/:xid/participant.js", ExperimentController, :participant_script
    get "/experiment/:xid/host.js", ExperimentController, :host_script
    get "/theme/:theme_id/description.js", ThemeController, :description_script
  end

  scope "/", XeeWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about

    # registration page
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    # login page
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    # theme page
    get "/explore/:page", ThemeController, :explore
    get "/theme/:theme_id", ThemeController, :theme

    # experiment page
    get "/experiment", ExperimentController, :shortcut
    get "/experiment/:xid", ExperimentController, :index
    get "/experiment/:xid/host", ExperimentController, :host
    get "/experiment/:xid/host/:id", ExperimentController, :control
    get "/experiment/host/:id", ExperimentController, :control
  end

  scope "/host", XeeWeb do
    pipe_through :browser # Use the default browser stack
    get "/", HostController, :index
    get "/index", HostController, :index
    post "/remove", HostController, :remove
    get "/experiment", HostController, :experiment
    post "/experiment/create", HostController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", XeeWeb do
  #   pipe_through :api
  # end
end

apps/xee/lib/xee_web/views/layout_view.ex
defmodule XeeWeb.LayoutView do
  use XeeWeb, :view
end

apps/xee/lib/xee_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Online Experiments System for Economic Education">
    <meta name="author" content="Ryohei HAYASHI">

    <%= if assigns[:title] do %>
      <title>XEE.JP - <%= @title %> -</title>
    <% else %>
      <title>XEE.JP</title>
    <% end %>

    <style type="text/css">
      .introbtn {
        background: -webkit-gradient(linear, left top, left bottom, from(#FFF), to(#333));*/
        color:#111;
        background-color: #90EE90;
        text-align: center;*/
        font-size: 0.9em;
        border: none;
        border-radius: 2px;
        display: inline-block;
        outline: 0;
        padding: 2px;
      }
      .drag-and-drop {
        cursor: move;
        z-index: 1000;
      }
      .drag {
        z-index: 1001;
      }
      html, body {height: 100%;}
      #main {min-height: 100%;}
    </style>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" />
    <link rel="shortcut icon" href="<%= static_path(@conn, "/favicon.ico") %>" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css" />
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.1.0/intro.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.1.0/introjs.min.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  </head>

  <body>
    <ul id="dropdown" class="dropdown-content">
      <li><a href="<%= host_path(@conn, :index) %>">実験管理画面</a></li>
      <li class="divider"></li>
      <li><%= link "ログアウト", to: session_path(@conn, :delete) %></li>
    </ul>
    <div class="row">
      <nav>
        <div class="nav-wrapper light-blue darken-3">
          <div class="col s12 m12 l8 offset-l2 offset-m1 offset-s1">
            <a href="/" class="brand-logo left" style="padding-left: 4%;">XEE.JP</a>
            <%= if assigns[:title] do %>
              <span class="brand-logo center hide-on-small-only"><%= @title %></span>
            <%= end %>
            <ul class="right">
              <%= if logged_in?(@conn) do %>
                <li><a class="dropdown-button" data-beloworigin="true" href="#!" data-activates="dropdown" style="padding: 0px 25%; min-width: 130px;"><%= current_user(@conn).name %></a></li>
              <% else %>
                <%= unless assigns[:title] do %>
                  <li id='step_registration'><%= link "教師用ページ", to: registration_path(@conn, :new) %></li>
                  <li><%= link "ログイン", to: session_path(@conn, :new) %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <div class="container" id="main" role="main" >
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </div>

    <footer class="page-footer light-blue darken-3" style="padding:10px; text-align: center; width:100%;" id="footer">
      <div class="footer-copyright light-blue darken-3" style="overflow:visible; line-height:20px;">
        <ul>
          <li>&copy; 2015 <a href="https://www.facebook.com/hryohei" style="color: #FFFF00;">Ryohei HAYASHI</a> All Rights Reserved.</li>
          <li>Powered by <a href="<%= page_path(@conn, :about) %>"><font color="#FFFF00">Xee System</font></a>.</li>
        </ul>
      </div>
    </footer>

    <script>
      $(document).ready(function() {
        $('select').material_select();
      });
      $(".dropdown-button").dropdown();
      $('.modal-trigger').leanModal();
    </script>
  </body>
</html>