apps/xee/lib/xee_web/router.ex
defmodule XeeWeb.Router do
  use XeeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :js do
    plug :accepts, ["js"]
  end

  scope "/", XeeWeb do
    pipe_through :js
    get "/experiment/:xid/participant.js", ExperimentController, :participant_script
    get "/experiment/:xid/host.js", ExperimentController, :host_script
    get "/theme/:theme_id/description.js", ThemeController, :description_script
  end

  scope "/", XeeWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about

    # registration page
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    # login page
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    # theme page
    get "/explore/:page", ThemeController, :explore
    get "/theme/:theme_id", ThemeController, :theme

    # experiment page
    get "/experiment", ExperimentController, :shortcut
    get "/experiment/:xid", ExperimentController, :index
    get "/experiment/:xid/host", ExperimentController, :host
    get "/experiment/:xid/host/:id", ExperimentController, :control
    get "/experiment/host/:id", ExperimentController, :control
  end

  scope "/host", XeeWeb do
    pipe_through :browser # Use the default browser stack
    get "/", HostController, :index
    get "/index", HostController, :index
    post "/remove", HostController, :remove
    get "/experiment", HostController, :experiment
    post "/experiment/create", HostController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", XeeWeb do
  #   pipe_through :api
  # end
end

apps/xee/lib/xee_web/controllers/host_controller.ex
defmodule XeeWeb.HostController do
  use XeeWeb, :controller
  require Logger
  plug Xee.AuthenticationPlug

  def index(conn, _params) do
    user = conn.assigns[:host]
    experiment = Xee.HostServer.get(user.id)
    if experiment do
      experiment = Enum.filter_map(experiment,
       &(Xee.ExperimentServer.has?(&1)),
       &(Xee.ExperimentServer.get_info(&1)))
    end
    render conn, "index.html", csrf_token: get_csrf_token(), experiment: experiment
  end

  def remove(conn, %{"xid" => xid}) do
    user = conn.assigns[:host]

    if Xee.ExperimentServer.has?(xid) do
      %{x_token: token} = Xee.ExperimentServer.get_info(xid)
      pid = Xee.ExperimentServer.get(xid)
      Xee.ExperimentServer.remove(xid)
      Xee.TokenServer.drop(token)
      Xee.HostServer.drop(user.id, xid)
      Xee.Experiment.stop(pid)
    end
    conn
    |> redirect(to: "/host")
    |> halt
  end

  def experiment(conn, params) do
    user = conn.assigns[:host]
    themes = Xee.ThemeServer.get_all
              |> Map.to_list
              |> Enum.map(fn {_key, value} -> value end)
              |> Enum.filter(fn theme -> Xee.Theme.granted?(theme, user.name) end)
    if length(themes) == 0 do
      conn
      |> put_flash(:error, "There are no themes")
      |> redirect(to: "/host")
      |> halt
    else
      theme_id = Map.get(params, "theme_id", nil) || hd(themes).id
      render conn, "experiment.html", csrf_token: get_csrf_token(), experiment_name: "", theme_id: theme_id, themes: themes, x_token: Xee.TokenServer.generate_id
    end
  end

  def create(conn, %{"experiment_name" => name, "theme" => theme_id, "x_token" => x_token}) do
    if (String.length(name) == 0 || String.length(x_token) == 0) do
      conn
      |> put_flash(:error, "All fields are required")
      |> redirect(to: "/host/experiment?theme_id=#{theme_id}")
      |> halt
    else
      user = conn.assigns[:host]
      unless (Xee.TokenServer.has?(x_token)) do
        xid = Xee.TokenGenerator.generate
        themes = Xee.ThemeServer.get_all
                  |> Map.to_list
                  |> Enum.map(fn {_key, value} -> value end)
                  |> Enum.filter(fn theme -> Xee.Theme.granted?(theme, user.name) end)
        xtheme = Xee.ThemeServer.get(theme_id)
        true = Xee.Theme.granted?(xtheme, user.name)
        Xee.TokenServer.register(x_token, xid)
        {:ok, pid} = Xee.ExperimentServer.create(xid, xtheme.experiment, %{name: name, experiment: xtheme.experiment, theme: xtheme.name, x_token: x_token, xid: xid})
        Xee.Experiment.attach_meta(pid, user.id, x_token)
        Xee.HostServer.register(user.id, xid)
        ip = conn.remote_ip |> Tuple.to_list |> Enum.join(".")
        conn
        |> redirect(to: "/experiment/" <> xid <> "/host")
        |> halt
      else
        themes = Xee.ThemeServer.get_all
                  |> Map.to_list
                  |> Enum.map(fn {_key, value} -> value end)
                  |> Enum.filter(fn theme -> Xee.Theme.granted?(theme, user.name) end)
        conn
        |> put_flash(:error, "This ExperimentID is already being used.")
        |> render("experiment.html", csrf_token: get_csrf_token(), experiment_name: name, theme_id: theme_id, themes: themes, x_token: Xee.TokenServer.generate_id)
      end
    end
  end
end

apps/xee/lib/xee_web/views/host_view.ex
defmodule XeeWeb.HostView do
  use XeeWeb, :view
end

apps/xee/lib/xee_web/templates/host/experiment.html.eex
<form method="post" action="/host/experiment/create" style="margin: 5%;">
  <div class="row">
    <div class="card light-blue lighten-5 col s12 m12 l10">
      <div class="card-content">
        <span class="card-title">実験作成</span>
        <input type="hidden" name="_csrf_token" value="<%= @csrf_token %>">
        <div class="row" >
          <div class="input-field" >
            <div class="col s12 m12 l6" id="step1">
              <input type="text" placeholder="実験名" class="validate" id="experiment" name="experiment_name" value="<%= @experiment_name %>">
            <label>実験名</label>
            </div>
          </div>
        </div>
        <div class="row" >
          <div class="input-field">
            <div class="col s12 m12 l6" id="step2">
              <select id="theme" name="theme">
                <%= if @themes do %>
                  <%= for theme <- @themes do %>
                    <option value="<%= theme.id %>" <%= if theme.id == @theme_id do %>selected<% end %>><%= theme.name %></option>
                  <% end %>
                <% end %>
              </select>
              <label>実験テーマ</label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="input-field">
            <div class="col s12 m12 l6" id="step3">
              <input type="text" placeholder="Experiment ID" class="validate" id="x_token" name="x_token" placeholder="" value="<%= @x_token %>">
              <label>実験ID</label>
            </div>
          </div>
        </div>
      </div>
      <div class="card-action" style="position:static">
        <button id="step4" class="btn btn-primary pull-right"  type="submit">実験作成</button>
      </div>
    </div>
  </div>
</form>
<%= if @themes do %>
  <h4>実験テーマ一覧</h4>
  <hr>
  <table class="table striped">
    <thead>
      <tr>
        <th>#</th>
        <th>タイトル</th>
        <th>カテゴリ</th>
      </tr>
    </thead>
    <tbody>
      <%= for theme <- @themes do %>
        <tr>
          <td></td>
          <td><%= theme.name %></td>
          <td><%= Enum.join(theme.tags, ", ") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= if Map.has_key?(@conn.params, "intro") do %>
<script>
if ("<%= @conn.params["intro"] %>" == "true"){
  var intro = introJs().onchange(
    function(){
      switch(document.activeElement.id){
        case "theme":document.getElementById("x_token").focus();break;
        default:document.activeElement.blur();break;
      }
    }
    ).setOptions({
      'showButtons': false,
      'showBullets': false,
      'showStepNumbers':false
  })
  const step = [
    {
      element: '#step1',
      intro:"<p>実験名を入力してください。</p><br/><button type='button' class='btn grey black-text lighten-2 waves-effect' onClick='intro.exit()'>閉じる</button><button type='button' class='btn waves-effect waves-light' style='margin-left:10px' onClick='intro.nextStep()'>次へ</button>"
    },
    {
      element: '#step2',
      intro:"<p>実験テーマを選んでください。</p><br/><button type='button' class='btn grey black-text lighten-2 waves-effect' onClick='intro.exit()'>閉じる</button><button type='button' class='btn waves-effect waves-light' style='margin-left:10px' onClick='intro.nextStep()'>次へ</button>"
    },
    {
      element: '#step3',
      intro:"<p>実験IDを入力してください。</p><br/><button type='button' class='btn grey black-text lighten-2 waves-effect' onClick='intro.exit()'>閉じる</button><button type='button' class='btn waves-effect waves-light' style='margin-left:10px's onClick='intro.nextStep()'>次へ</button>"
    },
    {
      element: '#step4',
      intro:"<p>実験をはじめます。</p><br/><button type='button' class='btn grey black-text lighten-2 waves-effect' onClick='intro.exit()'>閉じる</button>"
    }
  ]
  intro = intro.setOption('steps',step)
  setTimeout(() => intro.start(), 60000)
}
document.getElementById("experiment").focus()
</script>
<% end %>

apps/xee/lib/xee_web/templates/host/index.html.eex
<div class="center-block" style="margin: 3%;">
  <h4>管理者画面</h4>
  <hr>
  <div style="margin-top: 3%">
    <font size="5">
      <div class="collection">
        <a class="collection-item" href="<%= theme_path(@conn, :explore, "list") %>">実験テーマ一覧</a>
        <a class="collection-item" href="<%= theme_path(@conn, :explore, "category") %>">実験テーマ一覧 (カテゴリ別)</a>
        <span id='step1'>
          <%= if Map.has_key?(@conn.params, "intro") do %>
            <a class="collection-item" href="<%= host_path(@conn, :experiment, intro: @conn.params["intro"]=="true") %>">
          <% else %>
            <a class="collection-item" href="<%= host_path(@conn, :experiment, intro: false) %>">
          <% end %>
            実験作成画面
          </a>
        </span>
      </div>
    </font>
  </div>
</div>
<div class="Container" style="margin: 3%;">
  <%= if @experiment do %>
    <h4>現在作成中の実験</h4>
    <hr>
    <font size="4">
      <table class="table striped">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>実験テーマ</th>
            <th>実験ID</th>
          </tr>
        </thead>
        <tbody>
          <%= for exp <- @experiment do %>
            <tr>
              <td style="text-align: center">
                <form method="post" action="/host/remove">
                  <button class="btn-floating red darken-4" type="submit" ><i class="tiny material-icons">delete</i></button>
                  <input type="hidden" name="_csrf_token" value="<%= @csrf_token %>">
                  <input type="hidden" name="xid" value="<%= exp[:xid] %>">
                </form>
              </td>
              <td><%= exp[:name] %></td>
              <td><%= exp[:theme] %></td>
              <td><a href="/experiment/<%= exp[:xid] %>/host" class="waves-effect waves-light btn" style="text-transform: none"><%= exp[:x_token] %></a></td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </font>
  <% end %>
</div>
<%= if Map.has_key?(@conn.params, "intro") do %>
<script>
if ("<%= @conn.params["intro"] %>" == "true") {
  var intro = introJs().setOptions({
    'showButtons': false,
    'showBullets': false,
    'showStepNumbers':false
  })
  const step = [
  {
    element: '#step1',
    intro:"こちらから実験を作成することができます。<br/><button type='button' class='btn grey black-text lighten-2 waves-effect' onClick='intro.exit()'>閉じる</button>"
  }]
  intro = intro.setOption('steps',step)
  setTimeout(() => intro.start(), 60000)
}
</script>
<% end %>